<a href="https://colab.research.google.com/github/RecSys-lab/Popcorn/blob/main/examples/colab/load_ml_thumbnail_emb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **🍿 Popcorn Framework in Google Colab**
### **Load MovieLens-25M Thumbnails (Embeddings)**

🎬 Popcorn Framework: [link](https://github.com/RecSys-lab/Popcorn)

## **[Step 1] Clone Popcorn Movie Recommender Tool**

Clone the framework into your `GDrive` and prepare it for experiments.

⚠️ You might see a *"Restart Session"* warning during the first run in Google Colab due to library version mismatches. This is expected! Accept the restart, re-run this cell, and continue!

In [1]:
# Clone the repo
!git clone https://github.com/RecSys-lab/Popcorn.git

# Install the required library
%cd Popcorn
!pip install -e .

# Add the repository to the Python path
import sys
sys.path.append('/content/Popcorn')

# Go back to the root
%cd ..

Cloning into 'Popcorn'...
remote: Enumerating objects: 2314, done.
remote: Counting objects: 100% (170/170), done.
remote: Compressing objects: 100% (129/129), done.
remote: Total 2314 (delta 86), reused 97 (delta 37), pack-reused 2144 (from 1)
Receiving objects: 100% (2314/2314), 4.54 MiB | 7.43 MiB/s, done.
Resolving deltas: 100% (1424/1424), done.
/content/Popcorn
Obtaining file:///content/Popcorn
  Preparing metadata (setup.py) ... done
Collecting setuptools==80.9.0 (from Popcorn==1.6.0)
  Downloading setuptools-80.9.0-py3-none-any.whl.metadata (6.6 kB)
Collecting PyYAML==6.0.2 (from Popcorn==1.6.0)
  Downloading PyYAML-6.0.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.1 kB)
Collecting requests==2.32.5 (from Popcorn==1.6.0)
  Downloading requests-2.32.5-py3-none-any.whl.metadata (4.9 kB)
Collecting pandas==2.3.0 (from Popcorn==1.6.0)
  Downloading pandas-2.3.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (91 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 91.2/91.2 kB 6.0 MB/s eta 0:00:00
Collecting numpy==2.3.2 (from Popcorn==1.6.0)
  Downloading numpy-2.3.2-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.1/62.1 kB 4.5 MB/s eta 0:00:00
Collecting scikit-learn==1.7.2 (from Popcorn==1.6.0)
  Downloading scikit_learn-1.7.2-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (11 kB)
Collecting yt-dlp==2025.9.26 (from Popcorn==1.6.0)
  Downloading yt_dlp-2025.9.26-py3-none-any.whl.metadata (175 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 175.9/175.9 kB 11.8 MB/s eta 0:00:00
Collecting opencv-python==4.11.0.86 (from Popcorn==1.6.0)
  Downloading opencv_python-4.11.0.86-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (20 kB)
Collecting keras==3.11.3 (from Popcorn==1.6.0)
  Downloading keras-3.11.3-py3-none-any.whl.metadata (5.9 kB)
Collecting torch==2.8.0 (from Popcorn==1.6.0)
  Downloading torch-2.8.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (30 kB)
Collecting cornac==2.3.3 (from Popcorn==1.6.0)
  Downloading cornac-2.3.3-cp312-cp312-manylinux1_x86_64.whl.metadata (51 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.4/51.4 kB 4.0 MB/s eta 0:00:00
Collecting openai==2.16.0 (from Popcorn==1.6.0)
  Downloading openai-2.16.0-py3-none-any.whl.metadata (29 kB)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from cornac==2.3.3->Popcorn==1.6.0) (1.16.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from cornac==2.3.3->Popcorn==1.6.0) (4.67.3)
Collecting powerlaw (from cornac==2.3.3->Popcorn==1.6.0)
  Downloading powerlaw-2.0.0-py3-none-any.whl.metadata (9.9 kB)
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from keras==3.11.3->Popcorn==1.6.0) (1.4.0)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras==3.11.3->Popcorn==1.6.0) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras==3.11.3->Popcorn==1.6.0) (0.1.0)
Requirement already satisfied: h5py in /usr/local/lib/python3.12/dist-packages (from keras==3.11.3->Popcorn==1.6.0) (3.16.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras==3.11.3->Popcorn==1.6.0) (0.19.0)
Requirement already satisfied: ml-dtypes in /usr/local/lib/python3.12/dist-packages (from keras==3.11.3->Popcorn==1.6.0) (0.5.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from keras==3.11.3->Popcorn==1.6.0) (26.0)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from openai==2.16.0->Popcorn==1.6.0) (4.13.0)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from openai==2.16.0->Popcorn==1.6.0) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from openai==2.16.0->Popcorn==1.6.0) (0.28.1)
Requirement already satisfied: jiter<1,>=0.10.0 in /usr/local/lib/python3.12/dist-packages (from openai==2.16.0->Popcorn==1.6.0) (0.14.0)
Requirement already satisfied: pydantic<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from openai==2.16.0->Popcorn==1.6.0) (2.12.3)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from openai==2.16.0->Popcorn==1.6.0) (1.3.1)
Requirement already satisfied: typing-extensions<5,>=4.11 in /usr/local/lib/python3.12/dist-packages (from openai==2.16.0->Popcorn==1.6.0) (4.15.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas==2.3.0->Popcorn==1.6.0) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas==2.3.0->Popcorn==1.6.0) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas==2.3.0->Popcorn==1.6.0) (2026.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests==2.32.5->Popcorn==1.6.0) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests==2.32.5->Popcorn==1.6.0) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests==2.32.5->Popcorn==1.6.0) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests==2.32.5->Popcorn==1.6.0) (2026.2.25)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn==1.7.2->Popcorn==1.6.0) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn==1.7.2->Popcorn==1.6.0) (3.6.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch==2.8.0->Popcorn==1.6.0) (3.25.2)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch==2.8.0->Popcorn==1.6.0) (1.14.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from torch==2.8.0->Popcorn==1.6.0) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch==2.8.0->Popcorn==1.6.0) (3.1.6)
Requirement already satisfied: fsspec in /usr/local/lib/python3.12/dist-packages (from torch==2.8.0->Popcorn==1.6.0) (2025.3.0)
Collecting nvidia-cuda-nvrtc-cu12==12.8.93 (from torch==2.8.0->Popcorn==1.6.0)
  Downloading nvidia_cuda_nvrtc_cu12-12.8.93-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cuda-runtime-cu12==12.8.90 (from torch==2.8.0->Popcorn==1.6.0)
  Downloading nvidia_cuda_runtime_cu12-12.8.90-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cuda-cupti-cu12==12.8.90 (from torch==2.8.0->Popcorn==1.6.0)
  Downloading nvidia_cuda_cupti_cu12-12.8.90-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cudnn-cu12==9.10.2.21 (from torch==2.8.0->Popcorn==1.6.0)
  Downloading nvidia_cudnn_cu12-9.10.2.21-py3-none-manylinux_2_27_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-cublas-cu12==12.8.4.1 (from torch==2.8.0->Popcorn==1.6.0)
  Downloading nvidia_cublas_cu12-12.8.4.1-py3-none-manylinux_2_27_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cufft-cu12==11.3.3.83 (from torch==2.8.0->Popcorn==1.6.0)
  Downloading nvidia_cufft_cu12-11.3.3.83-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-curand-cu12==10.3.9.90 (from torch==2.8.0->Popcorn==1.6.0)
  Downloading nvidia_curand_cu12-10.3.9.90-py3-none-manylinux_2_27_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cusolver-cu12==11.7.3.90 (from torch==2.8.0->Popcorn==1.6.0)
  Downloading nvidia_cusolver_cu12-11.7.3.90-py3-none-manylinux_2_27_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-cusparse-cu12==12.5.8.93 (from torch==2.8.0->Popcorn==1.6.0)
  Downloading nvidia_cusparse_cu12-12.5.8.93-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-cusparselt-cu12==0.7.1 (from torch==2.8.0->Popcorn==1.6.0)
  Downloading nvidia_cusparselt_cu12-0.7.1-py3-none-manylinux2014_x86_64.whl.metadata (7.0 kB)
Collecting nvidia-nccl-cu12==2.27.3 (from torch==2.8.0->Popcorn==1.6.0)
  Downloading nvidia_nccl_cu12-2.27.3-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (2.0 kB)
Collecting nvidia-nvtx-cu12==12.8.90 (from torch==2.8.0->Popcorn==1.6.0)
  Downloading nvidia_nvtx_cu12-12.8.90-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-nvjitlink-cu12==12.8.93 (from torch==2.8.0->Popcorn==1.6.0)
  Downloading nvidia_nvjitlink_cu12-12.8.93-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cufile-cu12==1.13.1.3 (from torch==2.8.0->Popcorn==1.6.0)
  Downloading nvidia_cufile_cu12-1.13.1.3-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Collecting triton==3.4.0 (from torch==2.8.0->Popcorn==1.6.0)
  Downloading triton-3.4.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (1.7 kB)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->openai==2.16.0->Popcorn==1.6.0) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai==2.16.0->Popcorn==1.6.0) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->openai==2.16.0->Popcorn==1.6.0) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->openai==2.16.0->Popcorn==1.6.0) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->openai==2.16.0->Popcorn==1.6.0) (0.4.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas==2.3.0->Popcorn==1.6.0) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch==2.8.0->Popcorn==1.6.0) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch==2.8.0->Popcorn==1.6.0) (3.0.3)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from powerlaw->cornac==2.3.3->Popcorn==1.6.0) (3.10.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras==3.11.3->Popcorn==1.6.0) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras==3.11.3->Popcorn==1.6.0) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras==3.11.3->Popcorn==1.6.0) (0.1.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->powerlaw->cornac==2.3.3->Popcorn==1.6.0) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->powerlaw->cornac==2.3.3->Popcorn==1.6.0) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->powerlaw->cornac==2.3.3->Popcorn==1.6.0) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->powerlaw->cornac==2.3.3->Popcorn==1.6.0) (1.5.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->powerlaw->cornac==2.3.3->Popcorn==1.6.0) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->powerlaw->cornac==2.3.3->Popcorn==1.6.0) (3.3.2)
Downloading cornac-2.3.3-cp312-cp312-manylinux1_x86_64.whl (31.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 31.2/31.2 MB 46.6 MB/s eta 0:00:00
Downloading keras-3.11.3-py3-none-any.whl (1.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 46.5 MB/s eta 0:00:00
Downloading numpy-2.3.2-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.6/16.6 MB 49.4 MB/s eta 0:00:00
Downloading openai-2.16.0-py3-none-any.whl (1.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 49.5 MB/s eta 0:00:00
Downloading opencv_python-4.11.0.86-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (63.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.0/63.0 MB 9.4 MB/s eta 0:00:00
Downloading pandas-2.3.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.0/12.0 MB 45.6 MB/s eta 0:00:00
Downloading PyYAML-6.0.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (767 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 767.5/767.5 kB 42.1 MB/s eta 0:00:00
Downloading requests-2.32.5-py3-none-any.whl (64 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.7/64.7 kB 4.8 MB/s eta 0:00:00
Downloading scikit_learn-1.7.2-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (9.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.5/9.5 MB 51.5 MB/s eta 0:00:00
Downloading setuptools-80.9.0-py3-none-any.whl (1.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 43.8 MB/s eta 0:00:00
Downloading torch-2.8.0-cp312-cp312-manylinux_2_28_x86_64.whl (887.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 887.9/887.9 MB 802.0 kB/s eta 0:00:00
Downloading yt_dlp-2025.9.26-py3-none-any.whl (3.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 51.8 MB/s eta 0:00:00
Downloading nvidia_cublas_cu12-12.8.4.1-py3-none-manylinux_2_27_x86_64.whl (594.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 594.3/594.3 MB 754.4 kB/s eta 0:00:00
Downloading nvidia_cuda_cupti_cu12-12.8.90-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (10.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.2/10.2 MB 113.1 MB/s eta 0:00:00
Downloading nvidia_cuda_nvrtc_cu12-12.8.93-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl (88.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 88.0/88.0 MB 8.5 MB/s eta 0:00:00
Downloading nvidia_cuda_runtime_cu12-12.8.90-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (954 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 954.8/954.8 kB 44.1 MB/s eta 0:00:00
Downloading nvidia_cudnn_cu12-9.10.2.21-py3-none-manylinux_2_27_x86_64.whl (706.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 706.8/706.8 MB 1.3 MB/s eta 0:00:00
Downloading nvidia_cufft_cu12-11.3.3.83-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (193.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 193.1/193.1 MB 6.0 MB/s eta 0:00:00
Downloading nvidia_cufile_cu12-1.13.1.3-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (1.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 61.2 MB/s eta 0:00:00
Downloading nvidia_curand_cu12-10.3.9.90-py3-none-manylinux_2_27_x86_64.whl (63.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.6/63.6 MB 12.7 MB/s eta 0:00:00
Downloading nvidia_cusolver_cu12-11.7.3.90-py3-none-manylinux_2_27_x86_64.whl (267.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 267.5/267.5 MB 5.5 MB/s eta 0:00:00
Downloading nvidia_cusparse_cu12-12.5.8.93-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (288.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 288.2/288.2 MB 5.2 MB/s eta 0:00:00
Downloading nvidia_cusparselt_cu12-0.7.1-py3-none-manylinux2014_x86_64.whl (287.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 287.2/287.2 MB 4.8 MB/s eta 0:00:00
Downloading nvidia_nccl_cu12-2.27.3-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (322.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 322.4/322.4 MB 4.1 MB/s eta 0:00:00
Downloading nvidia_nvjitlink_cu12-12.8.93-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl (39.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 39.3/39.3 MB 50.0 MB/s eta 0:00:00
Downloading nvidia_nvtx_cu12-12.8.90-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (89 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 90.0/90.0 kB 7.2 MB/s eta 0:00:00
Downloading triton-3.4.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (155.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 155.6/155.6 MB 6.4 MB/s eta 0:00:00
Downloading powerlaw-2.0.0-py3-none-any.whl (191 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 192.0/192.0 kB 13.8 MB/s eta 0:00:00
Installing collected packages: nvidia-cusparselt-cu12, yt-dlp, setuptools, requests, PyYAML, nvidia-nvtx-cu12, nvidia-nvjitlink-cu12, nvidia-nccl-cu12, nvidia-curand-cu12, nvidia-cufile-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, numpy, triton, pandas, opencv-python, nvidia-cusparse-cu12, nvidia-cufft-cu12, nvidia-cudnn-cu12, scikit-learn, openai, nvidia-cusolver-cu12, keras, torch, powerlaw, cornac, Popcorn
  Attempting uninstall: setuptools
    Found existing installation: setuptools 75.2.0
    Uninstalling setuptools-75.2.0:
      Successfully uninstalled setuptools-75.2.0
  Attempting uninstall: requests
    Found existing installation: requests 2.32.4
    Uninstalling requests-2.32.4:
      Successfully uninstalled requests-2.32.4
  Attempting uninstall: PyYAML
    Found existing installation: PyYAML 6.0.3
    Uninstalling PyYAML-6.0.3:
      Successfully uninstalled PyYAML-6.0.3
  Attempting uninstall: nvidia-nccl-cu12
    Found existing installation: nvidia-nccl-cu12 2.29.7
    Uninstalling nvidia-nccl-cu12-2.29.7:
      Successfully uninstalled nvidia-nccl-cu12-2.29.7
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2
  Attempting uninstall: pandas
    Found existing installation: pandas 2.2.2
    Uninstalling pandas-2.2.2:
      Successfully uninstalled pandas-2.2.2
  Attempting uninstall: opencv-python
    Found existing installation: opencv-python 4.13.0.92
    Uninstalling opencv-python-4.13.0.92:
      Successfully uninstalled opencv-python-4.13.0.92
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.6.1
    Uninstalling scikit-learn-1.6.1:
      Successfully uninstalled scikit-learn-1.6.1
  Attempting uninstall: openai
    Found existing installation: openai 2.31.0
    Uninstalling openai-2.31.0:
      Successfully uninstalled openai-2.31.0
  Attempting uninstall: keras
    Found existing installation: keras 3.13.2
    Uninstalling keras-3.13.2:
      Successfully uninstalled keras-3.13.2
  Attempting uninstall: torch
    Found existing installation: torch 2.10.0+cpu
    Uninstalling torch-2.10.0+cpu:
      Successfully uninstalled torch-2.10.0+cpu
  Running setup.py develop for Popcorn
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ipython 7.34.0 requires jedi>=0.16, which is not installed.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 2.3.0 which is incompatible.
google-colab 1.0.0 requires requests==2.32.4, but you have requests 2.32.5 which is incompatible.
tensorflow 2.19.0 requires numpy<2.2.0,>=1.26.0, but you have numpy 2.3.2 which is incompatible.
numba 0.60.0 requires numpy<2.1,>=1.22, but you have numpy 2.3.2 which is incompatible.
torchaudio 2.10.0+cpu requires torch==2.10.0, but you have torch 2.8.0 which is incompatible.
torchvision 0.25.0+cpu requires torch==2.10.0, but you have torch 2.8.0 which is incompatible.
keras-hub 0.26.0 requires keras>=3.13, but you have keras 3.11.3 which is incompatible.

/content

## 🚀 **[Step 2] Use the Framework**

### *1. Load Configurations and Imports*

In [1]:
import os
import json
import pandas as pd
from popcorn.utils import readConfigs

# Start the Framework
print("Welcome to 'Popcorn' 🍿! Starting the framework for your movie recommendation ...\n")

# Read the configuration file
configs = readConfigs("Popcorn/popcorn/config/config.yml")
# If properly read, print the configurations
if not configs:
    print("Error reading the configuration file!")

# Get common configurations
cfgMovieLens = configs["datasets"]["unimodal"]["movielens"]
downloadPath = cfgMovieLens["download_path"]

# Override (optional)
downloadPath = "/content/MovieLens"
print(f"- Changing download path from '{cfgMovieLens['download_path']}' to: {downloadPath}")

Welcome to 'Popcorn' 🍿! Starting the framework for your movie recommendation ...

- Reading the framework's configuration file ...
- Configuration file loaded successfully!
- Changing download path from 'E:/Datasets/MovieLens' to: /content/MovieLens

### *3-A. Load MovieLens 25M Thumbnail Embeddings of a Given Movie (Dino-V2)*

In [3]:
from popcorn.datasets.ml_thumbnail.helper_embedding import (
    loadMovieLensThumbnailEmbeddings,
    loadAllMovieLensThumbnailEmbeddings
)

# Variables
root = "/content/Thumbnails"
configs["datasets"]["unimodal"]["ml_thumbnail"]["variant"] = 'dino-v2'
configs["datasets"]["unimodal"]["ml_thumbnail"]["download_path"] = root

# Load thumbnail embeddings for a given part
partId = 1
variant = configs["datasets"]["unimodal"]["ml_thumbnail"]["variant"]
embeddingsDF = loadMovieLensThumbnailEmbeddings(partId, variant)

display(embeddingsDF)

- Fetching embeddings from 'https://huggingface.co/datasets/alitourani/movielens-25m-thumb/resolve/main/embedding_dino-v2/thumbnails_ml25m_part1.csv' ...
- 4973 thumbnail embeddings loaded successfully!

,movie_id,embd_0,embd_1,embd_2,embd_3,embd_4,embd_5,embd_6,embd_7,embd_8,...,embd_758,embd_759,embd_760,embd_761,embd_762,embd_763,embd_764,embd_765,embd_766,embd_767
0,1942,2.125778,-2.853538,0.421571,-0.214650,-2.970062,-0.674792,0.416913,-3.778838,2.950539,...,-1.142500,0.626598,-0.224494,-0.448315,0.975705,-0.394506,-0.030404,4.304875,0.994717,-1.756593
1,769,0.450203,-1.552321,0.798823,-0.619184,-2.231707,-0.240531,-0.347871,-0.445851,-0.003807,...,-0.165629,-1.737258,-0.244247,5.086960,-0.242577,-0.006920,0.336143,0.711827,0.857452,-0.453697
2,4081,2.072134,-1.186719,-0.508410,-0.399742,1.730432,-0.025055,0.494669,-0.039627,-3.460143,...,1.318741,-0.364072,-0.555628,0.725962,-5.266904,0.576226,-1.685522,-1.084686,0.056447,-0.468579
3,5096,-1.921417,-0.635945,-1.406060,0.166158,-0.874534,0.059273,-0.813507,-0.300950,1.947260,...,1.495625,0.441996,0.871382,-0.234851,1.113418,3.758470,-1.643225,-2.966198,2.484983,3.415607
4,4021,-0.212451,-1.480430,-2.206816,-0.337786,-0.407343,-0.091727,2.424892,-3.599121,-0.075178,...,1.360010,-3.259937,-0.560069,0.368761,-4.425858,-0.614728,-0.531113,2.267472,4.152867,-0.507449
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4968,867,-1.787048,-1.513229,-0.826912,0.827360,-0.623168,0.092526,-0.455013,-1.722492,-0.885144,...,-0.602697,-3.659181,0.090026,-1.697725,-0.677746,2.722641,-2.938432,0.688672,1.670598,2.848333
4969,3382,1.773036,-3.051218,-0.064513,-2.051598,0.698796,0.435483,-1.524208,-2.108181,-1.096828,...,1.614995,-0.470502,-1.334481,1.848188,-1.652750,0.172587,1.003116,2.904636,-0.399330,-0.761480
4970,4819,0.491290,-1.491588,0.075284,-2.868789,-1.686089,-0.339548,-0.625206,-0.606673,0.036625,...,0.732730,-1.434148,1.152860,4.570023,-1.126447,-0.804763,3.403417,1.966857,-0.198208,-0.899915
4971,2149,0.984703,-1.794276,1.465436,-4.180865,2.527924,-0.063085,1.205300,0.876208,-0.253408,...,1.797752,-2.518429,-2.806956,1.371760,-0.684899,1.031145,0.054694,-0.047665,2.545432,0.879640
4972,55,2.262199,1.009341,-0.716237,-2.181680,-0.944336,0.973288,0.395133,-2.224216,1.320672,...,1.419436,-2.903046,1.134694,-0.883815,0.139900,1.462426,-0.225468,1.796310,1.279629,-1.781336

### *3. Load MovieLens 25M Thumbnail Embeddings of a Given Movie (CLIP)*

In [4]:
from popcorn.datasets.ml_thumbnail.helper_embedding import (
    loadMovieLensThumbnailEmbeddings,
    loadAllMovieLensThumbnailEmbeddings
)

# Variables
root = "/content/Thumbnails"
configs["datasets"]["unimodal"]["ml_thumbnail"]["variant"] = 'clip'
configs["datasets"]["unimodal"]["ml_thumbnail"]["download_path"] = root

# Load thumbnail embeddings for a given part
partId = 1
variant = configs["datasets"]["unimodal"]["ml_thumbnail"]["variant"]
embeddingsDF = loadMovieLensThumbnailEmbeddings(partId, variant)

display(embeddingsDF)

- Fetching embeddings from 'https://huggingface.co/datasets/alitourani/movielens-25m-thumb/resolve/main/embedding_clip/thumbnails_ml25m_part1.csv' ...
- 4973 thumbnail embeddings loaded successfully!

,movie_id,embd_0,embd_1,embd_2,embd_3,embd_4,embd_5,embd_6,embd_7,embd_8,...,embd_502,embd_503,embd_504,embd_505,embd_506,embd_507,embd_508,embd_509,embd_510,embd_511
0,1942,-0.551034,-0.086195,-0.657327,-0.026818,-0.002183,-0.078195,-0.042363,0.139317,-0.597425,...,0.174070,-0.027197,-0.262116,-0.174292,-0.013038,0.076369,-0.551379,0.395493,-0.008919,0.156020
1,769,0.081049,0.124520,0.032162,-0.229247,0.028140,0.123065,-0.427793,-0.228886,0.167664,...,-0.016111,0.557394,0.887559,0.484936,0.259587,-0.047556,-0.003666,-0.005683,0.218479,0.361338
2,4081,-0.049222,-0.163759,-0.100745,0.041097,-0.062645,0.217830,0.338891,0.154446,0.050912,...,-0.184771,0.243721,-0.861994,-0.227354,0.241941,0.128528,-0.251119,0.391890,0.215022,0.029057
3,5096,-0.241385,-0.161590,-0.301480,-0.216324,0.433860,-0.018341,0.587810,0.208682,-0.247640,...,0.319003,0.077653,-0.290268,-0.590078,0.438203,-0.685061,-0.440378,0.061402,-0.115114,0.002935
4,4021,0.057023,-0.315022,0.306876,-0.365681,0.554589,-0.431197,-0.182805,-0.278638,-0.041597,...,0.035190,-0.173431,0.021550,-0.398643,-0.092934,0.535589,0.206964,0.210423,0.104175,0.189474
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4968,867,-0.033838,-0.167890,0.266035,0.096598,0.453108,0.269351,0.683655,-0.375035,-0.091021,...,0.163475,0.060022,-0.542978,-0.160903,0.318196,-0.462611,-0.403459,0.490964,0.011215,0.171493
4969,3382,0.311646,-0.258615,-0.309253,-0.241096,-0.352177,-0.233403,0.069526,0.127190,-0.049774,...,0.279708,0.561510,-0.224582,-0.170683,0.028952,-0.478667,-0.586661,0.156159,-0.312092,0.199969
4970,4819,0.181067,-0.684204,-0.190755,0.201817,0.314008,-0.466749,0.052022,-0.279475,-0.361032,...,0.120813,0.073146,0.821043,-0.105069,0.084800,-0.086986,-0.176982,-0.397834,-0.346970,0.118167
4971,2149,0.246790,-0.541310,0.527180,0.169773,-0.237450,0.232484,-0.153783,0.139914,-0.341176,...,0.001191,0.454760,0.293756,0.167113,0.193073,0.115905,0.132550,0.250968,0.254294,-0.085409
4972,55,-0.497082,-0.011664,0.259133,-0.230971,0.330941,-0.142101,0.361267,-0.286376,-0.142080,...,0.330301,-0.151056,-0.065111,-0.334640,0.361296,0.167021,-0.178469,-0.160605,0.078706,-0.361060

### *4. Load All ML-25M Thumbnail Embeddings*

In [5]:
# Load the Movie Thumbnail
allEmbeddingsDF = loadAllMovieLensThumbnailEmbeddings(variant)

display(allEmbeddingsDF)

- Fetching embeddings from 'https://huggingface.co/datasets/alitourani/movielens-25m-thumb/resolve/main/embedding_clip/thumbnails_ml25m_part1.csv' ...
- 4973 thumbnail embeddings loaded successfully!
- Fetching embeddings from 'https://huggingface.co/datasets/alitourani/movielens-25m-thumb/resolve/main/embedding_clip/thumbnails_ml25m_part2.csv' ...
- 4977 thumbnail embeddings loaded successfully!
- Fetching embeddings from 'https://huggingface.co/datasets/alitourani/movielens-25m-thumb/resolve/main/embedding_clip/thumbnails_ml25m_part3.csv' ...
- 4976 thumbnail embeddings loaded successfully!
- Fetching embeddings from 'https://huggingface.co/datasets/alitourani/movielens-25m-thumb/resolve/main/embedding_clip/thumbnails_ml25m_part4.csv' ...
- 4931 thumbnail embeddings loaded successfully!
- Fetching embeddings from 'https://huggingface.co/datasets/alitourani/movielens-25m-thumb/resolve/main/embedding_clip/thumbnails_ml25m_part5.csv' ...
- 4936 thumbnail embeddings loaded successfully!
- Fetching embeddings from 'https://huggingface.co/datasets/alitourani/movielens-25m-thumb/resolve/main/embedding_clip/thumbnails_ml25m_part6.csv' ...
- 4950 thumbnail embeddings loaded successfully!
- Fetching embeddings from 'https://huggingface.co/datasets/alitourani/movielens-25m-thumb/resolve/main/embedding_clip/thumbnails_ml25m_part7.csv' ...
- 4909 thumbnail embeddings loaded successfully!
- Fetching embeddings from 'https://huggingface.co/datasets/alitourani/movielens-25m-thumb/resolve/main/embedding_clip/thumbnails_ml25m_part8.csv' ...
- 4869 thumbnail embeddings loaded successfully!
- Fetching embeddings from 'https://huggingface.co/datasets/alitourani/movielens-25m-thumb/resolve/main/embedding_clip/thumbnails_ml25m_part9.csv' ...
- 4883 thumbnail embeddings loaded successfully!
- Fetching embeddings from 'https://huggingface.co/datasets/alitourani/movielens-25m-thumb/resolve/main/embedding_clip/thumbnails_ml25m_part10.csv' ...
- 4869 thumbnail embeddings loaded successfully!
- Fetching embeddings from 'https://huggingface.co/datasets/alitourani/movielens-25m-thumb/resolve/main/embedding_clip/thumbnails_ml25m_part11.csv' ...
- 4899 thumbnail embeddings loaded successfully!
- Fetching embeddings from 'https://huggingface.co/datasets/alitourani/movielens-25m-thumb/resolve/main/embedding_clip/thumbnails_ml25m_part12.csv' ...
- 4894 thumbnail embeddings loaded successfully!
- Fetching embeddings from 'https://huggingface.co/datasets/alitourani/movielens-25m-thumb/resolve/main/embedding_clip/thumbnails_ml25m_part13.csv' ...
- 2370 thumbnail embeddings loaded successfully!
- Loaded all thumbnail embeddings (total: 61436)! Sample:
   movie_id    embd_0    embd_1    embd_2    embd_3    embd_4    embd_5  \
0      1942 -0.551034 -0.086195 -0.657327 -0.026818 -0.002183 -0.078195
1       769  0.081049  0.124520  0.032162 -0.229247  0.028140  0.123065
2      4081 -0.049222 -0.163759 -0.100745  0.041097 -0.062645  0.217830

     embd_6    embd_7    embd_8  ...  embd_502  embd_503  embd_504  embd_505  \
0 -0.042363  0.139317 -0.597425  ...  0.174070 -0.027197 -0.262116 -0.174292
1 -0.427793 -0.228886  0.167664  ... -0.016111  0.557394  0.887559  0.484936
2  0.338891  0.154446  0.050912  ... -0.184771  0.243721 -0.861994 -0.227354

   embd_506  embd_507  embd_508  embd_509  embd_510  embd_511
0 -0.013038  0.076369 -0.551379  0.395493 -0.008919  0.156020
1  0.259587 -0.047556 -0.003666 -0.005683  0.218479  0.361338
2  0.241941  0.128528 -0.251119  0.391890  0.215022  0.029057

[3 rows x 513 columns]

,movie_id,embd_0,embd_1,embd_2,embd_3,embd_4,embd_5,embd_6,embd_7,embd_8,...,embd_502,embd_503,embd_504,embd_505,embd_506,embd_507,embd_508,embd_509,embd_510,embd_511
0,1942,-0.551034,-0.086195,-0.657327,-0.026818,-0.002183,-0.078195,-0.042363,0.139317,-0.597425,...,0.174070,-0.027197,-0.262116,-0.174292,-0.013038,0.076369,-0.551379,0.395493,-0.008919,0.156020
1,769,0.081049,0.124520,0.032162,-0.229247,0.028140,0.123065,-0.427793,-0.228886,0.167664,...,-0.016111,0.557394,0.887559,0.484936,0.259587,-0.047556,-0.003666,-0.005683,0.218479,0.361338
2,4081,-0.049222,-0.163759,-0.100745,0.041097,-0.062645,0.217830,0.338891,0.154446,0.050912,...,-0.184771,0.243721,-0.861994,-0.227354,0.241941,0.128528,-0.251119,0.391890,0.215022,0.029057
3,5096,-0.241385,-0.161590,-0.301480,-0.216324,0.433860,-0.018341,0.587810,0.208682,-0.247640,...,0.319003,0.077653,-0.290268,-0.590078,0.438203,-0.685061,-0.440378,0.061402,-0.115114,0.002935
4,4021,0.057023,-0.315022,0.306876,-0.365681,0.554589,-0.431197,-0.182805,-0.278638,-0.041597,...,0.035190,-0.173431,0.021550,-0.398643,-0.092934,0.535589,0.206964,0.210423,0.104175,0.189474
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61431,204014,-0.041857,-0.326336,0.258074,-0.555787,0.119985,-0.508181,-0.080518,-0.108408,0.193894,...,-0.374188,-0.017151,-0.412723,-0.302830,0.188567,0.018773,-0.318979,-0.289110,0.348969,0.171711
61432,208787,-0.268167,0.397092,0.454235,0.279969,-0.009914,0.088261,0.214099,0.161900,0.012003,...,0.220721,0.058967,0.477461,-0.159166,-0.137437,-0.193096,-0.508540,-0.044861,-0.015340,0.256364
61433,202787,-0.191335,0.267996,0.294323,0.148708,0.315602,-0.526138,0.188646,-0.388367,-0.346097,...,0.317224,-0.110661,0.500382,-0.348711,-0.039583,-0.027076,-0.072573,0.005899,-0.019277,0.162841
61434,204882,0.355858,0.734396,0.210703,0.415167,-0.245756,-0.347042,-0.207326,0.604489,-0.820385,...,-0.027752,0.273690,0.133411,0.179240,-0.048892,-0.009870,-0.287215,-0.240037,-0.284216,0.285854
61435,205012,-0.132084,0.164122,0.024963,-0.254660,-0.309650,-0.224262,0.299335,-0.301347,-0.601458,...,0.061138,-0.013035,-0.091585,-0.065881,0.370451,-0.226131,-0.319394,0.104901,-0.094258,0.292055